---
language: python
services: docker

env:
  global:
    - COLLECTION_NAMESPACE: geerlingguy
    - COLLECTION_NAME: k8s
  matrix:
    - MOLECULE_DISTRO: default

install:
  # Install test dependencies.
  - pip install molecule docker openshift

  # Install Ansible from source (only devel has full collection support).
  - cd ../
  - git clone https://github.com/ansible/ansible.git
  - cd ansible
  - source ./hacking/env-setup
  - cd ../

before_script:
  # Move the collection into the required path.
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-$COLLECTION_NAME ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  # Test k8s_manifests role and k8s_template module.
  - molecule test -s test-manifests
